### PR TITLE
Try and address comments from @richsalz

### LINKED ISSUE #25: Email suggestions from @richsalz
[Email suggestions](https://mailarchive.ietf.org/arch/msg/gendispatch/3m1ny_Zjhxfy8vTqp14cSgQsO84) from @richsalz:
>I am posting to the gendispatch list because that is where the document says discussion should happen.
> 
>In Section 3, Motivation, the MODML reference doesn’t really give guidance to chairs for this general case being discussed by >this document. It describes how WG chairs should act if they make their WG list moderated, which is different.
> 
>The term PR-Action should be defined when first used, I think.
> 
>In section 4.1, Scope, the sentence “If is not expected that the moderator team will be monitoring every IETF channel…” should appear much earlier in the document.
> 
>In Section 4.3, Appeals, this sentence confuses me: Disagreements with a decision by the IETF Chair can be brought to their attention.  Does “their” refer to the IETF Chair? And if so, is it reasonable to expect that the IETF Chair having decided will change their mind? Isn’t disagreements with IETF Chair decisions can be appealed?
> 
>Have you considered having some subset of the organizational bodies and ISOC appoint members or liaisons?

### PR DESCRIPTION
**Pull request by larseggert**
Fixes #25

### CODE REVIEW

**Comment by russhousley** [comment]
Mostly, I agree with this change, but the "uniform" application of moderation criteria in PR#31 does not meld well with these changes.  Discussion is needed.

**Review by becarpenter — DISMISSED** [review]
I respectfully disagree with Russ. I don't think the policy of actively monitoring some lists and not others violates the uniformity of the criteria etc.  It simply recognizes that some lists are more general than others and therefore deserve more attention.

**Comment by russhousley** [comment]
Brian, then we need to be more clear about what is "uniform".

**Comment by becarpenter** [comment]
The text says "The moderator team SHALL operate according to a consistent and uniform set of criteria, processes, and actions." I'm just not seeing what is unclear about that sentence .

**Comment by russhousley** [comment]
I do not think there will be "uniform" attention paid to the various channels, and I see this as one way to interpret this sentence.

**Comment by larseggert** [comment]
@russhousley my proposal for #33 is to remove `and uniform`. With that change, is there anything that needs to change wrt this PR?

**Pull request merged**
